Repository canonical/content-cache-k8s-operator, pull requests merged in 2024-01, with the labels that each got.

#65 Update license headers date
  actions.yaml
  charmcraft.yaml
  config.yaml
  content-cache_rock/entrypoint.sh
  content-cache_rock/rockcraft.yaml
  lib/charms/nginx_ingress_integrator/v0/ingress.py
  metadata.yaml
  pyproject.toml
  src/charm.py
  src/file_reader.py
  tests/conftest.py
  tests/integration/any_charm.py
  tests/integration/conftest.py
  tests/integration/test_core.py
  tests/unit/test_charm.py
  tox.ini
  trivy.yaml
Labels: Libraries: Out of sync, trivial

#66 Add pull request template
  .github/pull_request_template.md
  docs/how-to/contribute.md
  generate-src-docs.sh
  requirements.txt
  src-docs/charm.py.md
  src-docs/file_reader.py.md
  tox.ini
Labels: Libraries: Out of sync, trivial

#67 Add Prometheus exporter to ROCK
  content-cache_rock/rockcraft.yaml
  metadata.yaml
  src/charm.py
  tests/integration/conftest.py
Labels: Libraries: Out of sync

#68 Migrate to nginx_route
  .woke.yml
  config.yaml
  docs/tutorial/getting-started.md
  lib/charms/nginx_ingress_integrator/v0/ingress.py
  lib/charms/nginx_ingress_integrator/v0/nginx_route.py
  metadata.yaml
  src-docs/charm.py.md
  src/charm.py
  tests/integration/any_charm.py
  tests/integration/conftest.py
  tests/unit/test_charm.py
Labels: enhancement, Libraries: Out of sync

#70 Fix trivy exit-code
  trivy.yaml
Labels: Libraries: Out of sync, trivial
